//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedTransporte.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedTransporte.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bus_stop {
            get {
                object obj = ResourceManager.GetObject("bus_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_marker_distance {
            get {
                object obj = ResourceManager.GetObject("map_marker_distance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_marker_path {
            get {
                object obj = ResourceManager.GetObject("map_marker_path", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [
        ///    {
        ///        &quot;IdParada&quot;:1,
        ///        &quot;Codigo&quot;:&quot;1421&quot;,
        ///        &quot;Descripcion&quot;:&quot;Paseo de la Farola&quot;,
        ///        &quot;Latitud&quot;:-44142814,
        ///        &quot;Longitud&quot;:3671476
        ///    },
        ///    {
        ///        &quot;IdParada&quot;:2,
        ///        &quot;Codigo&quot;:&quot;1301&quot;,
        ///        &quot;Descripcion&quot;:&quot;Paseo Mtmo. Ciudad de Melilla - Paseo Farola&quot;,
        ///        &quot;Latitud&quot;:-44131126,
        ///        &quot;Longitud&quot;:3671534
        ///    },
        ///    {
        ///        &quot;IdParada&quot;:3,
        ///        &quot;Codigo&quot;:&quot;1802&quot;,
        ///        &quot;Descripcion&quot;:&quot;Pso. Mtmo. Cdad. de Melilla - Pza. Malagueta&quot;,
        ///        &quot;Latitud&quot;:-441 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Paradas {
            get {
                return ResourceManager.GetString("Paradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [
        ///    {
        ///        &quot;IdRuta&quot;:1,
        ///        &quot;Codigo&quot;:&quot;L18&quot;,
        ///        &quot;Descripcion&quot;:&quot;Ciudad Jardín - Teatinos&quot;
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:2,
        ///        &quot;Codigo&quot;:&quot;L29&quot;,
        ///        &quot;Descripcion&quot;:&quot;Jarazmín - El Palo&quot;
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:3,
        ///        &quot;Codigo&quot;:&quot;L30&quot;,
        ///        &quot;Descripcion&quot;:&quot;Alameda Principal - Mangas Verdes&quot;
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:4,
        ///        &quot;Codigo&quot;:&quot;L32&quot;,
        ///        &quot;Descripcion&quot;:&quot;Av. Andalucía - Limonar - Mayorazgo&quot;
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:5,
        ///        &quot;Codigo&quot;:&quot;L14&quot;, [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Rutas {
            get {
                return ResourceManager.GetString("Rutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [
        ///    {
        ///        &quot;IdRuta&quot;:1,
        ///        &quot;Orden&quot;:1,
        ///        &quot;IdTramo&quot;:1
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:1,
        ///        &quot;Orden&quot;:2,
        ///        &quot;IdTramo&quot;:4
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:1,
        ///        &quot;Orden&quot;:3,
        ///        &quot;IdTramo&quot;:5
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:1,
        ///        &quot;Orden&quot;:4,
        ///        &quot;IdTramo&quot;:23
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:1,
        ///        &quot;Orden&quot;:5,
        ///        &quot;IdTramo&quot;:16
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:2,
        ///        &quot;Orden&quot;:1,
        ///        &quot;IdTramo&quot;:25
        ///    },
        ///    {
        ///        &quot;IdRuta&quot;:2,
        ///        &quot;Orden&quot;: [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RutaTramo {
            get {
                return ResourceManager.GetString("RutaTramo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a     [
        ///	{
        ///        &quot;IdTramo&quot;:1,
        ///        &quot;Codigo&quot;:&quot;T1712&quot;,
        ///        &quot;IdOrigen&quot;:15,
        ///        &quot;IdDestino&quot;:14,
        ///        &quot;Longitud&quot;:8,
        ///        &quot;Duracion&quot;:5
        ///    },
        ///    {
        ///        &quot;IdTramo&quot;:2,
        ///        &quot;Codigo&quot;:&quot;T1713&quot;,
        ///        &quot;IdOrigen&quot;:15,
        ///        &quot;IdDestino&quot;:1,
        ///        &quot;Longitud&quot;:4,
        ///        &quot;Duracion&quot;:3
        ///    },
        ///    {
        ///        &quot;IdTramo&quot;:3,
        ///        &quot;Codigo&quot;:&quot;T1714&quot;,
        ///        &quot;IdOrigen&quot;:13,
        ///        &quot;IdDestino&quot;:1,
        ///        &quot;Longitud&quot;:4,
        ///        &quot;Duracion&quot;:7
        ///    },
        ///    {
        ///        &quot;IdTramo&quot;:4,
        ///        [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Tramos {
            get {
                return ResourceManager.GetString("Tramos", resourceCulture);
            }
        }
    }
}
